export const UI = {
	CHAT: document.querySelector('.main__chat'),
	TEMPLATE: document.querySelector('#SMS__SEND'),
	TEMPLATE_DATE: document.querySelector('#DATE'),
	TEMPLATE_NAME: document.querySelector('#NAME'),
	INPUT: document.querySelector('.form__input'),
	FORM: document.querySelector('.content__form'),
	BUTTON_SEND: document.querySelector('.content__button'),
	FORM_AUTHORIZATION: document.querySelector('.modalAuthorization-content__form'),
	INPUT_AUTHORIZATION: document.querySelector('.modalAuthorization-content__form__input'),
	BUTTON_AUTHORIZATION: document.querySelector('.modalAuthorization-content__btn'),
	FORM_CONFIRMATION: document.querySelector('.modalConfirmation-content__form'),
	INPUT_CONFIRMATION: document.querySelector('.modalConfirmation-content__form__input'),
	BUTTON_CONFIRMATION: document.querySelector('.modalConfirmation-content__btn'),
	FORM_SETTINGS: document.querySelector('.modal-content__form'),
	INPUT_SETTINGS: document.querySelector('.modal-content__form__input'),
	BUTTON_SETTINGS: document.querySelector('.modal-content__btn'),
	MODAL_AUTHORIZATION: document.getElementById('myModalAuthorization'),
	SPAN_AUTHORIZATION: document.getElementsByClassName("modalAuthorization-content__btnContinue")[0],
	MODAL_CONFIRMATION: document.getElementById('myModalConfirmation'),
	SPAN_CONFIRMATION: document.getElementsByClassName("modalConfirmation-content__btn")[0],
	BTN_AUTHORIZATION: document.getElementsByClassName("modalAuthorization-content__btn")[0],
	MODAL_SETTINGS: document.getElementById('myModal'),
	BTN_SETTINGS: document.getElementById('btn'),
	CLOSE_SETTINGS: document.getElementsByClassName("modal-content__close")[0],
	BUTTON_EXIT: document.querySelector('.button__exit'),
	
}